FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the Task Service code into the container
COPY task_service.py /app/

# Install Flask
RUN pip install flask

# Expose the port used by the Task Service
EXPOSE 5001

# Command to run the Task Service
CMD ["python", "task_service.py"]
